sudo: false
language: c
compiler:
  - gcc
  - clang
env:
  global:
   - secure: "UU7zF7dSLR7SwZS/B/5WBg/9QUrhVShMjU5b3xNKxnnOTfJGBoQRPECUkmfBU5txv4il+fRYt2+Ln7I3ySc8FE5gT+/vEOdVxKS1O38U9bgv37e+pjSDIK+9yC53qOTHDw4zn+wH0NhWE2Tm8EgYH8oGsDKIb23QgCIw03hldLFFAFO9fHKFaqEr1BNZ4Mpz6RSgH82DqCSWHdnWhy16Bk1zlebg0m5v+vJ2E9ngMqaYgyRkSWn6zwBlCHypV2bqxlixNtIRVebrR+3pVzy+/lCZATe1Y3obBfZtKKq3OgW6ACZ4D/oCebY6Zro/lFuJUidU3LsuHtbrt3dxOedeJs8xKdbu7gGSkalPDgMzSEB26Voway/bAlwxkmgz/A9mFPEiXVRX6FavRDPXCkGqhU8DFLVEBwWIvtqFTqvNVpKUtIzSVoF2137Q+exDnslPkCsaTthlXaS2QU1zsyqAsFE8m2xbNRKrDVGcAgV6IoXn8d+ox7fkxTPPzV5Qu7cChyYfV87Abe+TOUxO5mK3ibIeyU8QJOPqwnfG9aRACbvf6Yn3tx6TGqIYfEwXdbr4MgP1yKLIl1vtMauwDriIziIfzEjwJBtyxDlQpBAGcWidgN0pX9QyuIfqkxGkw3bjoa8vYC0Xe1jIpNQcuk5p3+75UJAT0SN3wY77J1DW6cs="
script:
  - make
addons:
  coverity_scan:
    project:
      name: "gebn/members"
      description: "An improved implementation of members(1)"
    notification_email: oss@gebn.co.uk
    build_command_prepend: make clean
    build_command: make
    branch_pattern: master
